[package]
# Semantic Versionning is used: https://semver.org/
version = "2.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Super Snap"
description="An extension that moves objects for you."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Example"

# Keywords for the extension
keywords = ["kit", "example"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import Super.Dot".
[[python.module]]
name = "Super.Snap"
